### ISSUE TITLE
Code checking and quality testing with Git hooks

### ISSUE THREAD

**Issue by GiorgiBeriashvili** [lomsa-dev/http-mock-adapter#4]
# Description

[Git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) is a mechanism to automate work whenever certain important events occur, such as commits and pull requests.

It is notable that there are numerous Git hooks managers that make working with Git hooks noticeably easier, such as [lefthook](https://github.com/Arkweid/lefthook).

Example configuration for `lefthook` (keep in mind that you will have to set up `lefthook` locally on your system):

```yml
pre-push:
  parallel: true
  commands:
    tests:
      run: flutter test

pre-commit:
  commands:
    pretty:
      glob: "*.dart"
      run: flutter format {staged_files} && git add {staged_files}
    linter:
      run: flutter analyze
```
